pipeline {
    agent any

    parameters {
        string(name: 'FILE_PATH', defaultValue: '', description: 'Dataset file path')
    }

    stages {

        stage('Start Pipeline') {
            steps {
                echo "Pipeline started successfully"
                echo "Dataset received: ${params.FILE_PATH}"
            }
        }

        stage('Setup Python Virtual Environment') {
            steps {
                sh '''
                echo "Creating Python virtual environment"

                python3 -m venv venv

                echo "Activating virtual environment"
                . venv/bin/activate

                echo "Upgrading pip"
                pip install --upgrade pip

                echo "Installing project dependencies"
                pip install -r preprocessing/requirements.txt
                '''
            }
        }

        stage('Run Preprocessing Pipeline') {
            steps {
                sh '''
                echo "Running preprocessing pipeline"

                . venv/bin/activate

                python preprocessing/main_pipeline.py ${FILE_PATH}
                '''
            }
        }

        stage('Pipeline Completed') {
            steps {
                echo "Preprocessing pipeline executed successfully"
            }
        }
    }
}